name: Create Issue on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  create-issue-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueTitle = "please Enable and trigger Dependabot security updates";
            const issueBody = "This repository should have Dependabot security updates enabled and running. Please ensure it's configured.";

            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });

            const existingIssue = issues.find(issue => issue.title === issueTitle);

            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody
              });
              console.log("✅ Issue created.");
            } else {
              console.log("⚠️ Issue already exists.");
            }
